version: "3.8"
services:
  flaskhello-application:
    container_name: flaskhello
    environment:
      - connectionstring:${connectionstring}
    image: hmahmood2351/helloworldflask
    ports:
    - target: 5000
      published: 80
      protocol: tcp