version: "3.8"
services:
  flaskhello-application:
    environment:
      - DATABASE_URI:${connectionstring} 
    image: hmahmood2351/helloworldflask
    ports:
    - target: 5000
      published: 80
      protocol: tcp